var C64Style = C64Style || {};

/**
* C64Style.Event Types
* @static
* @enum
*/
C64Style.EventType = {
  /** Emitted by an element when it moves */
  "ELEMENT_MOVED" : "ELEMENT_MOVED",
  /** Emitted by the screen before a render cycle */
  "BEFORE_RENDER" : "BEFORE_RENDER",
  /** Emitted by the screen after a render cycle */
  "AFTER_RENDER" : "AFTER_RENDER",
  /** Emitted when an element starts moving */
  "ELEMENT_STARTED_MOVING" : "ELEMENT_STARTED_MOVING",
  /** Emitted by a moving element when it stops moving */
  "ELEMENT_STOPPED_MOVING" : "ELEMENT_STOPPED_MOVING",
  "ELEMENT_COLLISION" : "ELEMENT_COLLISION",
  "ELEMENT_HIT_LEFT_EDGE" : "ELEMENT_HIT_LEFT_EDGE",
  "ELEMENT_HIT_RIGHT_EDGE" : "ELEMENT_HIT_RIGHT_EDGE",
  "ELEMENT_HIT_TOP_EDGE" : "ELEMENT_HIT_TOP_EDGE",
  "ELEMENT_HIT_BOTTOM_EDGE" : "ELEMENT_HIT_BOTTOM_EDGE",
  "SCREEN_PAUSED" : "SCREEN_PAUSED",
  "SCREEN_RESUMED" : "SCREEN_RESUMED",
  "MOUSE_MOVE" : "MOUSE_MOVE",
  "MOUSE_DOWN" : "MOUSE_DOWN",
  "MOUSE_UP" : "MOUSE_UP",
  "MOUSE_OVER_ELEMENT" : "MOUSE_OVER_ELEMENT",
  "MOUSE_MOVE_OVER_ELEMENT" : "MOUSE_MOVE_OVER_ELEMENT",
  "MOUSE_DOWN_ON_ELEMENT" : "MOUSE_DOWN_ON_ELEMENT",
  "MOUSE_UP_ON_ELEMENT" : "MOUSE_UP_ON_ELEMENT",
  "SPRITE_ANIMATION_DONE" : "SPRITE_ANIMATION_DONE"
};
