var C64Style = C64Style || {};

C64Style.EventType = {
  "ELEMENT_MOVED" : "ELEMENT_MOVED",
  "BEFORE_RENDER" : "BEFORE_RENDER",
  "AFTER_RENDER" : "AFTER_RENDER",
  "ELEMENT_STARTED_MOVING" : "ELEMENT_STARTED_MOVING",
  "ELEMENT_STOPPED_MOVING" : "ELEMENT_STOPPED_MOVING",
  "ELEMENT_COLLISION" : "ELEMENT_COLLISION",
  "ELEMENT_HIT_LEFT_EDGE" : "ELEMENT_HIT_LEFT_EDGE",
  "ELEMENT_HIT_RIGHT_EDGE" : "ELEMENT_HIT_RIGHT_EDGE",
  "ELEMENT_HIT_TOP_EDGE" : "ELEMENT_HIT_TOP_EDGE",
  "ELEMENT_HIT_BOTTOM_EDGE" : "ELEMENT_HIT_BOTTOM_EDGE",
  "ENGINE_PAUSED" : "ENGINE_PAUSED",
  "ENGINE_RESUMED" : "ENGINE_RESUMED"
};
