import { GfxLayer, ILayerProps } from "@shaunlusk/slgfx";
import { Color } from "../Color";
import { ColorIndexedPixPath } from "../ColorIndexedPixPath";
import { Palette } from "../Palette";
import { PixSprite } from "../PixSprite";
import { PixSpriteFrame } from "../PixSpriteFrame";
import { ITextLayerProps, TextLayer } from "../TextLayer";
import { BaseDemo, IBaseDemoProps } from "./BaseDemo";

const palettes = [
  // Default
  new Palette([
    new Color("rgb(25, 14, 14)"),
    new Color("rgb(255, 255, 255)"),
    new Color("rgb(216, 0, 0)"),
    new Color("rgb(255, 73, 73)"),
    new Color("rgb(196, 196, 196)"),
    new Color("rgb(255, 255, 235)"),
    new Color("rgb(204, 190, 180)")
  ]),
  // Orange
  new Palette([
    new Color("rgb(25, 14, 14)"),
    new Color("rgb(255, 128, 0)"),
    new Color("rgb(255, 255, 235)"),
    new Color("rgb(200, 215, 164)"),
    new Color("rgb(192, 96, 0)"),
    new Color("rgb(196, 128, 32)"),
    new Color("rgb(196, 128, 32)")
  ]),
  // Choco
  new Palette([
    new Color("rgb(25, 14, 14)"),
    new Color("rgb(128, 80, 32)"),
    new Color("rgb(255, 144, 144)"),
    new Color("rgb(255, 16, 96)"),
    new Color("rgb(64, 40, 16)"),
    new Color("rgb(164, 128, 64)"),
    new Color("rgb(164, 128, 64)"),
  ]),
  // Black
  new Palette([
    new Color("rgb(180, 225, 255)"),
    new Color("rgb(25, 14, 14)"),
    new Color("rgb(0, 216, 0)"),
    new Color("rgb(73, 255, 73)"),
    new Color("rgb(96, 96, 96)"),
    new Color("rgb(64, 64, 235)"),
    new Color("rgb(64, 64, 235)"),
  ]),
  // Blue
  new Palette([
    new Color("rgb(25, 14, 14)"),
    new Color("rgb(150, 164, 255)"),
    new Color("rgb(0, 0, 0)"),
    new Color("rgb(255, 255, 255)"),
    new Color("rgb(80, 116, 180)"),
    new Color("rgb(0, 80, 200)"),
    new Color("rgb(0, 80, 200)"),
  ]),
  // Charcoal
  new Palette([
    new Color("rgb(25, 14, 14)"),
    new Color("rgb(96, 96, 0)"),
    new Color("rgb(0, 0, 216)"),
    new Color("rgb(73, 73, 255)"),
    new Color("rgb(50, 50, 40)"),
    new Color("rgb(50, 50, 40)"),
    new Color("rgb(50, 50, 40)")
  ]),
];

const pixPathArray1 = [
  new ColorIndexedPixPath(5, 1, 0),
  new ColorIndexedPixPath(6, 1, 0),
  new ColorIndexedPixPath(10, 1, 0),
  new ColorIndexedPixPath(11, 1, 0),
  new ColorIndexedPixPath(4, 2, 0),
  new ColorIndexedPixPath(5, 2, 1),
  new ColorIndexedPixPath(6, 2, 0),
  new ColorIndexedPixPath(7, 2, 0),
  new ColorIndexedPixPath(8, 2, 0),
  new ColorIndexedPixPath(9, 2, 0),
  new ColorIndexedPixPath(10, 2, 0),
  new ColorIndexedPixPath(11, 2, 1),
  new ColorIndexedPixPath(12, 2, 0),
  new ColorIndexedPixPath(4, 3, 0),
  new ColorIndexedPixPath(5, 3, 1),
  new ColorIndexedPixPath(6, 3, 1),
  new ColorIndexedPixPath(7, 3, 1),
  new ColorIndexedPixPath(8, 3, 1),
  new ColorIndexedPixPath(9, 3, 1),
  new ColorIndexedPixPath(10, 3, 1),
  new ColorIndexedPixPath(11, 3, 1),
  new ColorIndexedPixPath(12, 3, 0),
  new ColorIndexedPixPath(4, 4, 0),
  new ColorIndexedPixPath(5, 4, 2),
  new ColorIndexedPixPath(6, 4, 2),
  new ColorIndexedPixPath(7, 4, 2),
  new ColorIndexedPixPath(8, 4, 3),
  new ColorIndexedPixPath(9, 4, 3),
  new ColorIndexedPixPath(10, 4, 2),
  new ColorIndexedPixPath(11, 4, 2),
  new ColorIndexedPixPath(12, 4, 0),
  new ColorIndexedPixPath(4, 5, 0),
  new ColorIndexedPixPath(5, 5, 1),
  new ColorIndexedPixPath(6, 5, 1),
  new ColorIndexedPixPath(7, 5, 1),
  new ColorIndexedPixPath(8, 5, 0),
  new ColorIndexedPixPath(9, 5, 1),
  new ColorIndexedPixPath(10, 5, 1),
  new ColorIndexedPixPath(11, 5, 0),
  new ColorIndexedPixPath(12, 5, 0),
  new ColorIndexedPixPath(4, 6, 0),
  new ColorIndexedPixPath(5, 6, 1),
  new ColorIndexedPixPath(6, 6, 1),
  new ColorIndexedPixPath(7, 6, 1),
  new ColorIndexedPixPath(8, 6, 0),
  new ColorIndexedPixPath(9, 6, 1),
  new ColorIndexedPixPath(10, 6, 1),
  new ColorIndexedPixPath(11, 6, 0),
  new ColorIndexedPixPath(12, 6, 0),
  new ColorIndexedPixPath(4, 7, 0),
  new ColorIndexedPixPath(5, 7, 4),
  new ColorIndexedPixPath(6, 7, 1),
  new ColorIndexedPixPath(7, 7, 1),
  new ColorIndexedPixPath(8, 7, 1),
  new ColorIndexedPixPath(9, 7, 1),
  new ColorIndexedPixPath(10, 7, 1),
  new ColorIndexedPixPath(11, 7, 4),
  new ColorIndexedPixPath(12, 7, 0),
  new ColorIndexedPixPath(4, 8, 0),
  new ColorIndexedPixPath(5, 8, 0),
  new ColorIndexedPixPath(6, 8, 4),
  new ColorIndexedPixPath(7, 8, 4),
  new ColorIndexedPixPath(8, 8, 4),
  new ColorIndexedPixPath(9, 8, 4),
  new ColorIndexedPixPath(10, 8, 4),
  new ColorIndexedPixPath(11, 8, 0),
  new ColorIndexedPixPath(3, 9, 0),
  new ColorIndexedPixPath(4, 9, 4),
  new ColorIndexedPixPath(5, 9, 1),
  new ColorIndexedPixPath(6, 9, 1),
  new ColorIndexedPixPath(7, 9, 1),
  new ColorIndexedPixPath(8, 9, 1),
  new ColorIndexedPixPath(9, 9, 1),
  new ColorIndexedPixPath(10, 9, 1),
  new ColorIndexedPixPath(11, 9, 0),
  new ColorIndexedPixPath(12, 9, 0),
  new ColorIndexedPixPath(3, 10, 0),
  new ColorIndexedPixPath(4, 10, 1),
  new ColorIndexedPixPath(5, 10, 1),
  new ColorIndexedPixPath(6, 10, 5),
  new ColorIndexedPixPath(7, 10, 5),
  new ColorIndexedPixPath(8, 10, 1),
  new ColorIndexedPixPath(9, 10, 1),
  new ColorIndexedPixPath(10, 10, 1),
  new ColorIndexedPixPath(11, 10, 6),
  new ColorIndexedPixPath(12, 10, 6),
  new ColorIndexedPixPath(13, 10, 0),
  new ColorIndexedPixPath(3, 11, 0),
  new ColorIndexedPixPath(4, 11, 4),
  new ColorIndexedPixPath(5, 11, 4),
  new ColorIndexedPixPath(6, 11, 5),
  new ColorIndexedPixPath(7, 11, 5),
  new ColorIndexedPixPath(8, 11, 1),
  new ColorIndexedPixPath(9, 11, 1),
  new ColorIndexedPixPath(10, 11, 1),
  new ColorIndexedPixPath(11, 11, 6),
  new ColorIndexedPixPath(12, 11, 6),
  new ColorIndexedPixPath(13, 11, 0),
  new ColorIndexedPixPath(4, 12, 0),
  new ColorIndexedPixPath(5, 12, 4),
  new ColorIndexedPixPath(6, 12, 4),
  new ColorIndexedPixPath(7, 12, 4),
  new ColorIndexedPixPath(8, 12, 4),
  new ColorIndexedPixPath(9, 12, 4),
  new ColorIndexedPixPath(10, 12, 4),
  new ColorIndexedPixPath(11, 12, 0),
  new ColorIndexedPixPath(12, 12, 0),
  new ColorIndexedPixPath(5, 13, 0),
  new ColorIndexedPixPath(6, 13, 4),
  new ColorIndexedPixPath(7, 13, 0),
  new ColorIndexedPixPath(8, 13, 0),
  new ColorIndexedPixPath(9, 13, 1),
  new ColorIndexedPixPath(10, 13, 1),
  new ColorIndexedPixPath(11, 13, 0),
  new ColorIndexedPixPath(5, 14, 0),
  new ColorIndexedPixPath(6, 14, 1),
  new ColorIndexedPixPath(7, 14, 1),
  new ColorIndexedPixPath(8, 14, 0),
  new ColorIndexedPixPath(9, 14, 0),
  new ColorIndexedPixPath(10, 14, 0),
  new ColorIndexedPixPath(11, 14, 0),
  new ColorIndexedPixPath(5, 15, 0),
  new ColorIndexedPixPath(6, 15, 0),
  new ColorIndexedPixPath(7, 15, 0),
  new ColorIndexedPixPath(8, 15, 0)
];

const   pixPathArray2 = [
  new ColorIndexedPixPath(5, 0, 0),
  new ColorIndexedPixPath(6, 0, 0),
  new ColorIndexedPixPath(10, 0, 0),
  new ColorIndexedPixPath(11, 0, 0),
  new ColorIndexedPixPath(4, 1, 0),
  new ColorIndexedPixPath(5, 1, 1),
  new ColorIndexedPixPath(6, 1, 0),
  new ColorIndexedPixPath(7, 1, 0),
  new ColorIndexedPixPath(8, 1, 0),
  new ColorIndexedPixPath(9, 1, 0),
  new ColorIndexedPixPath(10, 1, 0),
  new ColorIndexedPixPath(11, 1, 1),
  new ColorIndexedPixPath(12, 1, 0),
  new ColorIndexedPixPath(4, 2, 0),
  new ColorIndexedPixPath(5, 2, 1),
  new ColorIndexedPixPath(6, 2, 1),
  new ColorIndexedPixPath(7, 2, 1),
  new ColorIndexedPixPath(8, 2, 1),
  new ColorIndexedPixPath(9, 2, 1),
  new ColorIndexedPixPath(10, 2, 1),
  new ColorIndexedPixPath(11, 2, 1),
  new ColorIndexedPixPath(12, 2, 0),
  new ColorIndexedPixPath(4, 3, 0),
  new ColorIndexedPixPath(5, 3, 2),
  new ColorIndexedPixPath(6, 3, 2),
  new ColorIndexedPixPath(7, 3, 2),
  new ColorIndexedPixPath(8, 3, 3),
  new ColorIndexedPixPath(9, 3, 3),
  new ColorIndexedPixPath(10, 3, 2),
  new ColorIndexedPixPath(11, 3, 2),
  new ColorIndexedPixPath(12, 3, 0),
  new ColorIndexedPixPath(4, 4, 0),
  new ColorIndexedPixPath(5, 4, 1),
  new ColorIndexedPixPath(6, 4, 1),
  new ColorIndexedPixPath(7, 4, 1),
  new ColorIndexedPixPath(8, 4, 0),
  new ColorIndexedPixPath(9, 4, 1),
  new ColorIndexedPixPath(10, 4, 1),
  new ColorIndexedPixPath(11, 4, 0),
  new ColorIndexedPixPath(12, 4, 0),
  new ColorIndexedPixPath(4, 5, 0),
  new ColorIndexedPixPath(5, 5, 1),
  new ColorIndexedPixPath(6, 5, 1),
  new ColorIndexedPixPath(7, 5, 1),
  new ColorIndexedPixPath(8, 5, 0),
  new ColorIndexedPixPath(9, 5, 1),
  new ColorIndexedPixPath(10, 5, 1),
  new ColorIndexedPixPath(11, 5, 0),
  new ColorIndexedPixPath(12, 5, 0),
  new ColorIndexedPixPath(4, 6, 0),
  new ColorIndexedPixPath(5, 6, 4),
  new ColorIndexedPixPath(6, 6, 1),
  new ColorIndexedPixPath(7, 6, 1),
  new ColorIndexedPixPath(8, 6, 1),
  new ColorIndexedPixPath(9, 6, 1),
  new ColorIndexedPixPath(10, 6, 1),
  new ColorIndexedPixPath(11, 6, 4),
  new ColorIndexedPixPath(12, 6, 0),
  new ColorIndexedPixPath(5, 7, 0),
  new ColorIndexedPixPath(6, 7, 4),
  new ColorIndexedPixPath(7, 7, 4),
  new ColorIndexedPixPath(8, 7, 4),
  new ColorIndexedPixPath(9, 7, 4),
  new ColorIndexedPixPath(10, 7, 4),
  new ColorIndexedPixPath(11, 7, 5),
  new ColorIndexedPixPath(12, 7, 5),
  new ColorIndexedPixPath(13, 7, 0),
  new ColorIndexedPixPath(4, 8, 0),
  new ColorIndexedPixPath(5, 8, 1),
  new ColorIndexedPixPath(6, 8, 1),
  new ColorIndexedPixPath(7, 8, 1),
  new ColorIndexedPixPath(8, 8, 1),
  new ColorIndexedPixPath(9, 8, 1),
  new ColorIndexedPixPath(10, 8, 1),
  new ColorIndexedPixPath(11, 8, 5),
  new ColorIndexedPixPath(12, 8, 5),
  new ColorIndexedPixPath(13, 8, 0),
  new ColorIndexedPixPath(4, 9, 0),
  new ColorIndexedPixPath(5, 9, 4),
  new ColorIndexedPixPath(6, 9, 1),
  new ColorIndexedPixPath(7, 9, 1),
  new ColorIndexedPixPath(8, 9, 1),
  new ColorIndexedPixPath(9, 9, 1),
  new ColorIndexedPixPath(10, 9, 1),
  new ColorIndexedPixPath(11, 9, 4),
  new ColorIndexedPixPath(12, 9, 0),
  new ColorIndexedPixPath(5, 10, 0),
  new ColorIndexedPixPath(6, 10, 4),
  new ColorIndexedPixPath(7, 10, 1),
  new ColorIndexedPixPath(8, 10, 1),
  new ColorIndexedPixPath(9, 10, 1),
  new ColorIndexedPixPath(10, 10, 4),
  new ColorIndexedPixPath(11, 10, 0),
  new ColorIndexedPixPath(3, 11, 0),
  new ColorIndexedPixPath(4, 11, 0),
  new ColorIndexedPixPath(5, 11, 0),
  new ColorIndexedPixPath(6, 11, 4),
  new ColorIndexedPixPath(7, 11, 4),
  new ColorIndexedPixPath(8, 11, 4),
  new ColorIndexedPixPath(9, 11, 4),
  new ColorIndexedPixPath(10, 11, 4),
  new ColorIndexedPixPath(11, 11, 4),
  new ColorIndexedPixPath(12, 11, 0),
  new ColorIndexedPixPath(13, 11, 0),
  new ColorIndexedPixPath(14, 11, 0),
  new ColorIndexedPixPath(3, 12, 0),
  new ColorIndexedPixPath(4, 12, 1),
  new ColorIndexedPixPath(5, 12, 4),
  new ColorIndexedPixPath(6, 12, 4),
  new ColorIndexedPixPath(7, 12, 0),
  new ColorIndexedPixPath(8, 12, 0),
  new ColorIndexedPixPath(9, 12, 0),
  new ColorIndexedPixPath(10, 12, 0),
  new ColorIndexedPixPath(11, 12, 4),
  new ColorIndexedPixPath(12, 12, 1),
  new ColorIndexedPixPath(13, 12, 1),
  new ColorIndexedPixPath(14, 12, 0),
  new ColorIndexedPixPath(3, 13, 0),
  new ColorIndexedPixPath(4, 13, 1),
  new ColorIndexedPixPath(5, 13, 0),
  new ColorIndexedPixPath(6, 13, 0),
  new ColorIndexedPixPath(10, 13, 0),
  new ColorIndexedPixPath(11, 13, 1),
  new ColorIndexedPixPath(12, 13, 1),
  new ColorIndexedPixPath(13, 13, 0),
  new ColorIndexedPixPath(3, 14, 0),
  new ColorIndexedPixPath(4, 14, 0),
  new ColorIndexedPixPath(11, 14, 0),
  new ColorIndexedPixPath(12, 14, 0)
];

const   pixPathArray3 = [
  new ColorIndexedPixPath(5, 1, 0),
  new ColorIndexedPixPath(6, 1, 0),
  new ColorIndexedPixPath(10, 1, 0),
  new ColorIndexedPixPath(11, 1, 0),
  new ColorIndexedPixPath(4, 2, 0),
  new ColorIndexedPixPath(5, 2, 1),
  new ColorIndexedPixPath(6, 2, 0),
  new ColorIndexedPixPath(7, 2, 0),
  new ColorIndexedPixPath(8, 2, 0),
  new ColorIndexedPixPath(9, 2, 0),
  new ColorIndexedPixPath(10, 2, 0),
  new ColorIndexedPixPath(11, 2, 1),
  new ColorIndexedPixPath(12, 2, 0),
  new ColorIndexedPixPath(4, 3, 0),
  new ColorIndexedPixPath(5, 3, 1),
  new ColorIndexedPixPath(6, 3, 1),
  new ColorIndexedPixPath(7, 3, 1),
  new ColorIndexedPixPath(8, 3, 1),
  new ColorIndexedPixPath(9, 3, 1),
  new ColorIndexedPixPath(10, 3, 1),
  new ColorIndexedPixPath(11, 3, 1),
  new ColorIndexedPixPath(12, 3, 0),
  new ColorIndexedPixPath(4, 4, 0),
  new ColorIndexedPixPath(5, 4, 2),
  new ColorIndexedPixPath(6, 4, 2),
  new ColorIndexedPixPath(7, 4, 2),
  new ColorIndexedPixPath(8, 4, 3),
  new ColorIndexedPixPath(9, 4, 3),
  new ColorIndexedPixPath(10, 4, 2),
  new ColorIndexedPixPath(11, 4, 2),
  new ColorIndexedPixPath(12, 4, 0),
  new ColorIndexedPixPath(4, 5, 0),
  new ColorIndexedPixPath(5, 5, 1),
  new ColorIndexedPixPath(6, 5, 1),
  new ColorIndexedPixPath(7, 5, 1),
  new ColorIndexedPixPath(8, 5, 0),
  new ColorIndexedPixPath(9, 5, 1),
  new ColorIndexedPixPath(10, 5, 1),
  new ColorIndexedPixPath(11, 5, 0),
  new ColorIndexedPixPath(12, 5, 0),
  new ColorIndexedPixPath(4, 6, 0),
  new ColorIndexedPixPath(5, 6, 1),
  new ColorIndexedPixPath(6, 6, 1),
  new ColorIndexedPixPath(7, 6, 1),
  new ColorIndexedPixPath(8, 6, 0),
  new ColorIndexedPixPath(9, 6, 1),
  new ColorIndexedPixPath(10, 6, 1),
  new ColorIndexedPixPath(11, 6, 0),
  new ColorIndexedPixPath(12, 6, 0),
  new ColorIndexedPixPath(4, 7, 0),
  new ColorIndexedPixPath(5, 7, 4),
  new ColorIndexedPixPath(6, 7, 1),
  new ColorIndexedPixPath(7, 7, 1),
  new ColorIndexedPixPath(8, 7, 1),
  new ColorIndexedPixPath(9, 7, 1),
  new ColorIndexedPixPath(10, 7, 1),
  new ColorIndexedPixPath(11, 7, 4),
  new ColorIndexedPixPath(12, 7, 0),
  new ColorIndexedPixPath(5, 8, 0),
  new ColorIndexedPixPath(6, 8, 4),
  new ColorIndexedPixPath(7, 8, 4),
  new ColorIndexedPixPath(8, 8, 4),
  new ColorIndexedPixPath(9, 8, 4),
  new ColorIndexedPixPath(10, 8, 4),
  new ColorIndexedPixPath(11, 8, 0),
  new ColorIndexedPixPath(4, 9, 0),
  new ColorIndexedPixPath(5, 9, 1),
  new ColorIndexedPixPath(6, 9, 1),
  new ColorIndexedPixPath(7, 9, 1),
  new ColorIndexedPixPath(8, 9, 1),
  new ColorIndexedPixPath(9, 9, 1),
  new ColorIndexedPixPath(10, 9, 1),
  new ColorIndexedPixPath(11, 9, 0),
  new ColorIndexedPixPath(4, 10, 0),
  new ColorIndexedPixPath(5, 10, 4),
  new ColorIndexedPixPath(6, 10, 1),
  new ColorIndexedPixPath(7, 10, 1),
  new ColorIndexedPixPath(8, 10, 1),
  new ColorIndexedPixPath(9, 10, 1),
  new ColorIndexedPixPath(10, 10, 5),
  new ColorIndexedPixPath(11, 10, 5),
  new ColorIndexedPixPath(12, 10, 0),
  new ColorIndexedPixPath(5, 11, 0),
  new ColorIndexedPixPath(6, 11, 1),
  new ColorIndexedPixPath(7, 11, 1),
  new ColorIndexedPixPath(8, 11, 1),
  new ColorIndexedPixPath(9, 11, 4),
  new ColorIndexedPixPath(10, 11, 5),
  new ColorIndexedPixPath(11, 11, 5),
  new ColorIndexedPixPath(12, 11, 0),
  new ColorIndexedPixPath(5, 12, 0),
  new ColorIndexedPixPath(6, 12, 4),
  new ColorIndexedPixPath(7, 12, 4),
  new ColorIndexedPixPath(8, 12, 4),
  new ColorIndexedPixPath(9, 12, 4),
  new ColorIndexedPixPath(10, 12, 4),
  new ColorIndexedPixPath(11, 12, 0),
  new ColorIndexedPixPath(5, 13, 0),
  new ColorIndexedPixPath(6, 13, 1),
  new ColorIndexedPixPath(7, 13, 1),
  new ColorIndexedPixPath(8, 13, 0),
  new ColorIndexedPixPath(9, 13, 0),
  new ColorIndexedPixPath(10, 13, 4),
  new ColorIndexedPixPath(11, 13, 0),
  new ColorIndexedPixPath(5, 14, 0),
  new ColorIndexedPixPath(6, 14, 0),
  new ColorIndexedPixPath(7, 14, 0),
  new ColorIndexedPixPath(8, 14, 0),
  new ColorIndexedPixPath(9, 14, 0),
  new ColorIndexedPixPath(10, 14, 1),
  new ColorIndexedPixPath(11, 14, 1),
  new ColorIndexedPixPath(12, 14, 0),
  new ColorIndexedPixPath(9, 15, 0),
  new ColorIndexedPixPath(10, 15, 0),
  new ColorIndexedPixPath(11, 15, 0),
  new ColorIndexedPixPath(12, 15, 0)
];

const   pixPathArray4 = [
  new ColorIndexedPixPath(5, 1, 0),
  new ColorIndexedPixPath(6, 1, 0),
  new ColorIndexedPixPath(10, 1, 0),
  new ColorIndexedPixPath(11, 1, 0),
  new ColorIndexedPixPath(4, 2, 0),
  new ColorIndexedPixPath(5, 2, 1),
  new ColorIndexedPixPath(6, 2, 0),
  new ColorIndexedPixPath(7, 2, 0),
  new ColorIndexedPixPath(8, 2, 0),
  new ColorIndexedPixPath(9, 2, 0),
  new ColorIndexedPixPath(10, 2, 0),
  new ColorIndexedPixPath(11, 2, 1),
  new ColorIndexedPixPath(12, 2, 0),
  new ColorIndexedPixPath(4, 3, 0),
  new ColorIndexedPixPath(5, 3, 1),
  new ColorIndexedPixPath(6, 3, 1),
  new ColorIndexedPixPath(7, 3, 1),
  new ColorIndexedPixPath(8, 3, 1),
  new ColorIndexedPixPath(9, 3, 1),
  new ColorIndexedPixPath(10, 3, 1),
  new ColorIndexedPixPath(11, 3, 1),
  new ColorIndexedPixPath(12, 3, 0),
  new ColorIndexedPixPath(4, 4, 0),
  new ColorIndexedPixPath(5, 4, 2),
  new ColorIndexedPixPath(6, 4, 2),
  new ColorIndexedPixPath(7, 4, 2),
  new ColorIndexedPixPath(8, 4, 3),
  new ColorIndexedPixPath(9, 4, 3),
  new ColorIndexedPixPath(10, 4, 2),
  new ColorIndexedPixPath(11, 4, 2),
  new ColorIndexedPixPath(12, 4, 0),
  new ColorIndexedPixPath(4, 5, 0),
  new ColorIndexedPixPath(5, 5, 1),
  new ColorIndexedPixPath(6, 5, 1),
  new ColorIndexedPixPath(7, 5, 1),
  new ColorIndexedPixPath(8, 5, 0),
  new ColorIndexedPixPath(9, 5, 1),
  new ColorIndexedPixPath(10, 5, 1),
  new ColorIndexedPixPath(11, 5, 0),
  new ColorIndexedPixPath(12, 5, 0),
  new ColorIndexedPixPath(4, 6, 0),
  new ColorIndexedPixPath(5, 6, 1),
  new ColorIndexedPixPath(6, 6, 1),
  new ColorIndexedPixPath(7, 6, 1),
  new ColorIndexedPixPath(8, 6, 0),
  new ColorIndexedPixPath(9, 6, 1),
  new ColorIndexedPixPath(10, 6, 1),
  new ColorIndexedPixPath(11, 6, 0),
  new ColorIndexedPixPath(12, 6, 0),
  new ColorIndexedPixPath(4, 7, 0),
  new ColorIndexedPixPath(5, 7, 4),
  new ColorIndexedPixPath(6, 7, 1),
  new ColorIndexedPixPath(7, 7, 1),
  new ColorIndexedPixPath(8, 7, 1),
  new ColorIndexedPixPath(9, 7, 1),
  new ColorIndexedPixPath(10, 7, 1),
  new ColorIndexedPixPath(11, 7, 4),
  new ColorIndexedPixPath(12, 7, 0),
  new ColorIndexedPixPath(4, 8, 0),
  new ColorIndexedPixPath(5, 8, 0),
  new ColorIndexedPixPath(6, 8, 4),
  new ColorIndexedPixPath(7, 8, 4),
  new ColorIndexedPixPath(8, 8, 4),
  new ColorIndexedPixPath(9, 8, 4),
  new ColorIndexedPixPath(10, 8, 4),
  new ColorIndexedPixPath(11, 8, 0),
  new ColorIndexedPixPath(3, 9, 0),
  new ColorIndexedPixPath(4, 9, 4),
  new ColorIndexedPixPath(5, 9, 1),
  new ColorIndexedPixPath(6, 9, 1),
  new ColorIndexedPixPath(7, 9, 1),
  new ColorIndexedPixPath(8, 9, 1),
  new ColorIndexedPixPath(9, 9, 1),
  new ColorIndexedPixPath(10, 9, 1),
  new ColorIndexedPixPath(11, 9, 0),
  new ColorIndexedPixPath(12, 9, 0),
  new ColorIndexedPixPath(3, 10, 0),
  new ColorIndexedPixPath(4, 10, 1),
  new ColorIndexedPixPath(5, 10, 1),
  new ColorIndexedPixPath(6, 10, 5),
  new ColorIndexedPixPath(7, 10, 5),
  new ColorIndexedPixPath(8, 10, 1),
  new ColorIndexedPixPath(9, 10, 1),
  new ColorIndexedPixPath(10, 10, 1),
  new ColorIndexedPixPath(11, 10, 6),
  new ColorIndexedPixPath(12, 10, 6),
  new ColorIndexedPixPath(13, 10, 0),
  new ColorIndexedPixPath(3, 11, 0),
  new ColorIndexedPixPath(4, 11, 4),
  new ColorIndexedPixPath(5, 11, 4),
  new ColorIndexedPixPath(6, 11, 5),
  new ColorIndexedPixPath(7, 11, 5),
  new ColorIndexedPixPath(8, 11, 1),
  new ColorIndexedPixPath(9, 11, 1),
  new ColorIndexedPixPath(10, 11, 1),
  new ColorIndexedPixPath(11, 11, 6),
  new ColorIndexedPixPath(12, 11, 6),
  new ColorIndexedPixPath(13, 11, 0),
  new ColorIndexedPixPath(4, 12, 0),
  new ColorIndexedPixPath(5, 12, 4),
  new ColorIndexedPixPath(6, 12, 4),
  new ColorIndexedPixPath(7, 12, 4),
  new ColorIndexedPixPath(8, 12, 4),
  new ColorIndexedPixPath(9, 12, 4),
  new ColorIndexedPixPath(10, 12, 4),
  new ColorIndexedPixPath(11, 12, 0),
  new ColorIndexedPixPath(12, 12, 0),
  new ColorIndexedPixPath(5, 13, 0),
  new ColorIndexedPixPath(6, 13, 0),
  new ColorIndexedPixPath(7, 13, 1),
  new ColorIndexedPixPath(8, 13, 1),
  new ColorIndexedPixPath(9, 13, 4),
  new ColorIndexedPixPath(10, 13, 0),
  new ColorIndexedPixPath(11, 13, 0),
  new ColorIndexedPixPath(6, 14, 0),
  new ColorIndexedPixPath(7, 14, 0),
  new ColorIndexedPixPath(8, 14, 0),
  new ColorIndexedPixPath(9, 14, 1),
  new ColorIndexedPixPath(10, 14, 1),
  new ColorIndexedPixPath(11, 14, 0),
  new ColorIndexedPixPath(8, 15, 0),
  new ColorIndexedPixPath(9, 15, 0),
  new ColorIndexedPixPath(10, 15, 0),
  new ColorIndexedPixPath(11, 15, 0)
];

const pixPathArray5 = [
  new ColorIndexedPixPath(5, 0, 0),
  new ColorIndexedPixPath(6, 0, 0),
  new ColorIndexedPixPath(10, 0, 0),
  new ColorIndexedPixPath(11, 0, 0),
  new ColorIndexedPixPath(4, 1, 0),
  new ColorIndexedPixPath(5, 1, 1),
  new ColorIndexedPixPath(6, 1, 0),
  new ColorIndexedPixPath(7, 1, 0),
  new ColorIndexedPixPath(8, 1, 0),
  new ColorIndexedPixPath(9, 1, 0),
  new ColorIndexedPixPath(10, 1, 0),
  new ColorIndexedPixPath(11, 1, 1),
  new ColorIndexedPixPath(12, 1, 0),
  new ColorIndexedPixPath(4, 2, 0),
  new ColorIndexedPixPath(5, 2, 1),
  new ColorIndexedPixPath(6, 2, 1),
  new ColorIndexedPixPath(7, 2, 1),
  new ColorIndexedPixPath(8, 2, 1),
  new ColorIndexedPixPath(9, 2, 1),
  new ColorIndexedPixPath(10, 2, 1),
  new ColorIndexedPixPath(11, 2, 1),
  new ColorIndexedPixPath(12, 2, 0),
  new ColorIndexedPixPath(4, 3, 0),
  new ColorIndexedPixPath(5, 3, 2),
  new ColorIndexedPixPath(6, 3, 2),
  new ColorIndexedPixPath(7, 3, 2),
  new ColorIndexedPixPath(8, 3, 3),
  new ColorIndexedPixPath(9, 3, 3),
  new ColorIndexedPixPath(10, 3, 2),
  new ColorIndexedPixPath(11, 3, 2),
  new ColorIndexedPixPath(12, 3, 0),
  new ColorIndexedPixPath(4, 4, 0),
  new ColorIndexedPixPath(5, 4, 1),
  new ColorIndexedPixPath(6, 4, 1),
  new ColorIndexedPixPath(7, 4, 1),
  new ColorIndexedPixPath(8, 4, 0),
  new ColorIndexedPixPath(9, 4, 1),
  new ColorIndexedPixPath(10, 4, 1),
  new ColorIndexedPixPath(11, 4, 0),
  new ColorIndexedPixPath(12, 4, 0),
  new ColorIndexedPixPath(4, 5, 0),
  new ColorIndexedPixPath(5, 5, 1),
  new ColorIndexedPixPath(6, 5, 1),
  new ColorIndexedPixPath(7, 5, 1),
  new ColorIndexedPixPath(8, 5, 0),
  new ColorIndexedPixPath(9, 5, 1),
  new ColorIndexedPixPath(10, 5, 1),
  new ColorIndexedPixPath(11, 5, 0),
  new ColorIndexedPixPath(12, 5, 0),
  new ColorIndexedPixPath(4, 6, 0),
  new ColorIndexedPixPath(5, 6, 4),
  new ColorIndexedPixPath(6, 6, 1),
  new ColorIndexedPixPath(7, 6, 1),
  new ColorIndexedPixPath(8, 6, 1),
  new ColorIndexedPixPath(9, 6, 1),
  new ColorIndexedPixPath(10, 6, 1),
  new ColorIndexedPixPath(11, 6, 4),
  new ColorIndexedPixPath(12, 6, 0),
  new ColorIndexedPixPath(13, 6, 0),
  new ColorIndexedPixPath(4, 7, 0),
  new ColorIndexedPixPath(5, 7, 0),
  new ColorIndexedPixPath(6, 7, 4),
  new ColorIndexedPixPath(7, 7, 4),
  new ColorIndexedPixPath(8, 7, 4),
  new ColorIndexedPixPath(9, 7, 4),
  new ColorIndexedPixPath(10, 7, 4),
  new ColorIndexedPixPath(11, 7, 0),
  new ColorIndexedPixPath(12, 7, 5),
  new ColorIndexedPixPath(13, 7, 5),
  new ColorIndexedPixPath(14, 7, 0),
  new ColorIndexedPixPath(3, 8, 0),
  new ColorIndexedPixPath(4, 8, 1),
  new ColorIndexedPixPath(5, 8, 4),
  new ColorIndexedPixPath(6, 8, 1),
  new ColorIndexedPixPath(7, 8, 1),
  new ColorIndexedPixPath(8, 8, 1),
  new ColorIndexedPixPath(9, 8, 1),
  new ColorIndexedPixPath(10, 8, 1),
  new ColorIndexedPixPath(11, 8, 4),
  new ColorIndexedPixPath(12, 8, 5),
  new ColorIndexedPixPath(13, 8, 5),
  new ColorIndexedPixPath(14, 8, 0),
  new ColorIndexedPixPath(3, 9, 0),
  new ColorIndexedPixPath(4, 9, 5),
  new ColorIndexedPixPath(5, 9, 5),
  new ColorIndexedPixPath(6, 9, 4),
  new ColorIndexedPixPath(7, 9, 1),
  new ColorIndexedPixPath(8, 9, 1),
  new ColorIndexedPixPath(9, 9, 1),
  new ColorIndexedPixPath(10, 9, 1),
  new ColorIndexedPixPath(11, 9, 4),
  new ColorIndexedPixPath(12, 9, 4),
  new ColorIndexedPixPath(13, 9, 0),
  new ColorIndexedPixPath(3, 10, 0),
  new ColorIndexedPixPath(4, 10, 5),
  new ColorIndexedPixPath(5, 10, 5),
  new ColorIndexedPixPath(6, 10, 1),
  new ColorIndexedPixPath(7, 10, 1),
  new ColorIndexedPixPath(8, 10, 1),
  new ColorIndexedPixPath(9, 10, 1),
  new ColorIndexedPixPath(10, 10, 1),
  new ColorIndexedPixPath(11, 10, 0),
  new ColorIndexedPixPath(12, 10, 0),
  new ColorIndexedPixPath(4, 11, 0),
  new ColorIndexedPixPath(5, 11, 0),
  new ColorIndexedPixPath(6, 11, 4),
  new ColorIndexedPixPath(7, 11, 4),
  new ColorIndexedPixPath(8, 11, 4),
  new ColorIndexedPixPath(9, 11, 4),
  new ColorIndexedPixPath(10, 11, 4),
  new ColorIndexedPixPath(11, 11, 0),
  new ColorIndexedPixPath(6, 12, 0),
  new ColorIndexedPixPath(7, 12, 4),
  new ColorIndexedPixPath(8, 12, 1),
  new ColorIndexedPixPath(9, 12, 1),
  new ColorIndexedPixPath(10, 12, 0),
  new ColorIndexedPixPath(6, 13, 0),
  new ColorIndexedPixPath(7, 13, 1),
  new ColorIndexedPixPath(8, 13, 1),
  new ColorIndexedPixPath(9, 13, 0),
  new ColorIndexedPixPath(7, 14, 0),
  new ColorIndexedPixPath(8, 14, 0)
];
const pixPathArray6 = [
  new ColorIndexedPixPath(5, 1, 0),
  new ColorIndexedPixPath(6, 1, 0),
  new ColorIndexedPixPath(10, 1, 0),
  new ColorIndexedPixPath(11, 1, 0),
  new ColorIndexedPixPath(4, 2, 0),
  new ColorIndexedPixPath(5, 2, 1),
  new ColorIndexedPixPath(6, 2, 0),
  new ColorIndexedPixPath(7, 2, 0),
  new ColorIndexedPixPath(8, 2, 0),
  new ColorIndexedPixPath(9, 2, 0),
  new ColorIndexedPixPath(10, 2, 0),
  new ColorIndexedPixPath(11, 2, 1),
  new ColorIndexedPixPath(12, 2, 0),
  new ColorIndexedPixPath(4, 3, 0),
  new ColorIndexedPixPath(5, 3, 1),
  new ColorIndexedPixPath(6, 3, 1),
  new ColorIndexedPixPath(7, 3, 1),
  new ColorIndexedPixPath(8, 3, 1),
  new ColorIndexedPixPath(9, 3, 1),
  new ColorIndexedPixPath(10, 3, 1),
  new ColorIndexedPixPath(11, 3, 1),
  new ColorIndexedPixPath(12, 3, 0),
  new ColorIndexedPixPath(4, 4, 0),
  new ColorIndexedPixPath(5, 4, 2),
  new ColorIndexedPixPath(6, 4, 2),
  new ColorIndexedPixPath(7, 4, 2),
  new ColorIndexedPixPath(8, 4, 3),
  new ColorIndexedPixPath(9, 4, 3),
  new ColorIndexedPixPath(10, 4, 2),
  new ColorIndexedPixPath(11, 4, 2),
  new ColorIndexedPixPath(12, 4, 0),
  new ColorIndexedPixPath(4, 5, 0),
  new ColorIndexedPixPath(5, 5, 1),
  new ColorIndexedPixPath(6, 5, 1),
  new ColorIndexedPixPath(7, 5, 1),
  new ColorIndexedPixPath(8, 5, 0),
  new ColorIndexedPixPath(9, 5, 1),
  new ColorIndexedPixPath(10, 5, 1),
  new ColorIndexedPixPath(11, 5, 0),
  new ColorIndexedPixPath(12, 5, 0),
  new ColorIndexedPixPath(4, 6, 0),
  new ColorIndexedPixPath(5, 6, 1),
  new ColorIndexedPixPath(6, 6, 1),
  new ColorIndexedPixPath(7, 6, 1),
  new ColorIndexedPixPath(8, 6, 0),
  new ColorIndexedPixPath(9, 6, 1),
  new ColorIndexedPixPath(10, 6, 1),
  new ColorIndexedPixPath(11, 6, 0),
  new ColorIndexedPixPath(12, 6, 0),
  new ColorIndexedPixPath(4, 7, 0),
  new ColorIndexedPixPath(5, 7, 4),
  new ColorIndexedPixPath(6, 7, 1),
  new ColorIndexedPixPath(7, 7, 1),
  new ColorIndexedPixPath(8, 7, 1),
  new ColorIndexedPixPath(9, 7, 1),
  new ColorIndexedPixPath(10, 7, 1),
  new ColorIndexedPixPath(11, 7, 4),
  new ColorIndexedPixPath(12, 7, 0),
  new ColorIndexedPixPath(4, 8, 0),
  new ColorIndexedPixPath(5, 8, 0),
  new ColorIndexedPixPath(6, 8, 4),
  new ColorIndexedPixPath(7, 8, 4),
  new ColorIndexedPixPath(8, 8, 4),
  new ColorIndexedPixPath(9, 8, 4),
  new ColorIndexedPixPath(10, 8, 4),
  new ColorIndexedPixPath(11, 8, 0),
  new ColorIndexedPixPath(12, 8, 0),
  new ColorIndexedPixPath(13, 8, 0),
  new ColorIndexedPixPath(3, 9, 0),
  new ColorIndexedPixPath(4, 9, 1),
  new ColorIndexedPixPath(5, 9, 1),
  new ColorIndexedPixPath(6, 9, 1),
  new ColorIndexedPixPath(7, 9, 1),
  new ColorIndexedPixPath(8, 9, 1),
  new ColorIndexedPixPath(9, 9, 1),
  new ColorIndexedPixPath(10, 9, 1),
  new ColorIndexedPixPath(11, 9, 4),
  new ColorIndexedPixPath(12, 9, 5),
  new ColorIndexedPixPath(13, 9, 5),
  new ColorIndexedPixPath(14, 9, 0),
  new ColorIndexedPixPath(3, 10, 0),
  new ColorIndexedPixPath(4, 10, 4),
  new ColorIndexedPixPath(5, 10, 5),
  new ColorIndexedPixPath(6, 10, 5),
  new ColorIndexedPixPath(7, 10, 1),
  new ColorIndexedPixPath(8, 10, 1),
  new ColorIndexedPixPath(9, 10, 1),
  new ColorIndexedPixPath(10, 10, 1),
  new ColorIndexedPixPath(11, 10, 4),
  new ColorIndexedPixPath(12, 10, 5),
  new ColorIndexedPixPath(13, 10, 5),
  new ColorIndexedPixPath(14, 10, 0),
  new ColorIndexedPixPath(4, 11, 0),
  new ColorIndexedPixPath(5, 11, 5),
  new ColorIndexedPixPath(6, 11, 5),
  new ColorIndexedPixPath(7, 11, 1),
  new ColorIndexedPixPath(8, 11, 1),
  new ColorIndexedPixPath(9, 11, 1),
  new ColorIndexedPixPath(10, 11, 1),
  new ColorIndexedPixPath(11, 11, 0),
  new ColorIndexedPixPath(12, 11, 0),
  new ColorIndexedPixPath(13, 11, 0),
  new ColorIndexedPixPath(5, 12, 0),
  new ColorIndexedPixPath(6, 12, 4),
  new ColorIndexedPixPath(7, 12, 4),
  new ColorIndexedPixPath(8, 12, 4),
  new ColorIndexedPixPath(9, 12, 4),
  new ColorIndexedPixPath(10, 12, 4),
  new ColorIndexedPixPath(11, 12, 0),
  new ColorIndexedPixPath(6, 13, 0),
  new ColorIndexedPixPath(7, 13, 4),
  new ColorIndexedPixPath(8, 13, 4),
  new ColorIndexedPixPath(9, 13, 4),
  new ColorIndexedPixPath(10, 13, 0),
  new ColorIndexedPixPath(11, 13, 0),
  new ColorIndexedPixPath(6, 14, 0),
  new ColorIndexedPixPath(7, 14, 1),
  new ColorIndexedPixPath(8, 14, 1),
  new ColorIndexedPixPath(9, 14, 0),
  new ColorIndexedPixPath(10, 14, 0),
  new ColorIndexedPixPath(6, 15, 0),
  new ColorIndexedPixPath(7, 15, 0),
  new ColorIndexedPixPath(8, 15, 0),
  new ColorIndexedPixPath(9, 15, 0)
];

export class PaletteDemo2 extends BaseDemo {
  private _sprite1: PixSprite;

  constructor(props: IBaseDemoProps) {
    const rows = 8;
    const cols = 34;
    const scaleX = 2;
    const scaleY = 2;
    const superProps = {
      ...props,
      scaleX,
      scaleY,
      rows,
      cols
    };
    super(superProps);
    
    const textLayer = this.panel.createLayer<TextLayer, ITextLayerProps>("TextLayer", {scaleX, scaleY});
    const gfxLayer = this.panel.createLayer<GfxLayer, ILayerProps>("GfxLayer");

    this._sprite1 = new PixSprite({
      gfxPanel: this.panel,
      x:10, y:16,
      scaleX:2, scaleY:2,
      frames:[
        new PixSpriteFrame(pixPathArray1, 200),
        new PixSpriteFrame(pixPathArray2, 200),
        new PixSpriteFrame(pixPathArray3, 200),
        new PixSpriteFrame(pixPathArray4, 200),
        new PixSpriteFrame(pixPathArray5, 200),
        new PixSpriteFrame(pixPathArray6, 200)
      ]
    });
    gfxLayer.addElement(this._sprite1);

    textLayer.writeText("Click the buttons below", 6, 2, Color.WHITE);
    textLayer.writeText("to change Neko's colors.", 6, 3, Color.WHITE);
  
    this.initializePaletteColors();
    this.panel.render();


  }

  public applyPalette(idx: number) {
    this._sprite1.setPalette(palettes[idx]);
  }

  private initializePaletteColors() {
    const inputs = document.getElementsByName("paletteColor");
    for (let i = 0; i < inputs.length; i++) {
      const input = inputs[i] as HTMLInputElement;
      input.value = this._sprite1.getPaletteColor(i).value;
    }
  }

  public applyCustomPalette() {
    const inputs = document.getElementsByName("paletteColor");
    for (let i = 0; i < inputs.length; i++) {
      const input = inputs[i] as HTMLInputElement;
      this._sprite1.setPaletteColor(i, new Color(input.value));
    }
  }
}
